### PR TITLE
OH bonds generation fix

### PR DESCRIPTION
**Pull request by ajotcham**
I think the OH wasn't generating in your environment because the TMCOH_rxnmap.in path wasn't changed from before.

### CODE REVIEW

**Comment by tmweigand** [comment]
hmmm. I am still not getting any OH bonds to form. If it is working on Bridges, then it is on me and I will figure it out. Let me know please.

**Comment by tmweigand** [comment]
I also noticed you made this change: ```delete_atoms overlap 1.5 TMCs all mol yes #aj switch from 1.0```

Can you explain why you made that? Riley's method is a published method so if we change anything we need to be very careful and ensure that we understand exactly what the changes do.

**Comment by ajotcham** [comment]
That was an oversight I just noticed that too an hour ago. I originally did it awhile ago when we were first having trouble packing the system in the first place but that was only due to the mult variable being too big. I changed the tolerance at first to allow more atoms to potentially stay in the system but that's obviously not needed now so I've changed it back to 1.0.

**Comment by tmweigand** [comment]
ok great! Good job on flagging it with your initials so we could find it again.

**Comment by ajotcham** [comment]
Still working on this trying to figure out the issue because on my other repository it forms the OH bonds pretty quickly then moves on after it breaks the loop but in this one it just isn't forming the OH bonds like yours so I'm checking to find any meaningful differences between the two environments.

**Comment by tmweigand** [comment]
ok sounds good. This is very frustrating.

**Comment by tmweigand** [comment]
@ajotcham Any progress on this? What have you tried so far? I am going to look into this later today.

**Comment by ajotcham** [comment]
I've tried testing a lot of things in isolation in hopes I could find the cause but it still isn't forming OH bonds in this repository versus my old one. 

- I checked all relevant molecule files as well as the TMCOH_rxnmap.in file just to make sure it was identical to the working repo. I didn't find any differences in files so I don't think its an issue with that.
- In line 156 the "react rxn1 all ${BONDFREQ} 0.0 5.0 mol 3 mol4 ..." I changed BONDFREQ just to see if a higher frequency would form even one OH bond and it didn't so I changed it back to its original value of 50 above. Then I changed the 5.0 in that line to 10.0 because that value dictates the proximity for the reaction to occur in the simulation, that also didn't help either so I changed it back to 5.0. I didn't plan on changing these values permanently but just to see if a higher tolerance changed anything for OH bond formation, but it didn't. 
- Below this line under "variable OPEN_C equal count(Cls)" I added a print statement to make sure there were even open chlorides for the TMCOH rxn to occur and when I ran it there were open Cls in the system so I could eliminate that as a potential issue as well.

**Comment by tmweigand** [comment]
hmmm okay. sounds like you are going about it correctly. 

Is this working on your local machine but not Bridges? Are you using the new verison of LAMMPS on Bridges? Can you post your submit script here for me? I just want to make sure you are getting the correct version. 

Could you also post a successful and an unsuccessful log.lammps file here as well?

**Comment by ajotcham** [comment]
I've been debugging locally because the same issue comes up on Bridges where it gets to the OH bond formation step but never forms one and just loops through that step until the simulation times out. When I talk about the working file I'm referring to the old Riley file structure repository I was using before. 

[log_lammps_NOTWORKING.txt](https://github.com/user-attachments/files/17464194/log_lammps_NOTWORKING.txt)
[log_lammps_WORKING.txt](https://github.com/user-attachments/files/17464217/log_lammps_WORKING.txt)

**Comment by tmweigand** [comment]
ok. So with the old folder structure it works but with the new one it does not? That is the only change between them?

If that is correct, I would do the following:

1. Copy the working folder structure somewhere completely new and see if that runs? 

2. Methodically change this folder structure to be similar to the new ones and see when it breaks.

**Comment by ajotcham** [comment]
Ok I'll try doing that today and we can go over it tomorrow in our meeting.

**Comment by tmweigand** [comment]
This may be of use. In the output that is not working we have:
```
60 atoms in group NUM_AMIDE
MAX_BONDS = 60
WARNING: Fix bond/react: The BondingIDs section title has been deprecated. Please use InitiatorIDs instead. (src/REACTION/fix_bond_react.cpp:4033)
dynamic group bond_react_MASTER_group defined
dynamic group statted_grp_REACT defined
```

and the one that is working :
```
60 atoms in group NUM_AMIDE
dynamic group bond_react_MASTER_group defined
dynamic group statted_grp_REACT defined
```


But this is for amide and not OH.

**Pull request merged**
